project: FP_prediction_set
seed: 17 

data:
  dir: "/data/rbg/users/klingmin/projects/MS_processing/data/data_splits/random_split_pos"
  batch_size: 128
  num_workers: 2
  bin_resolution: 1.0
  max_da: 1000
  max_MS_peaks: 1000
  FP_type: "maccs"

model:
  train_params:
    lr: 0.0004
    weight_decay: 0.1

  MS_encoder:
    n_unique_adducts: 10
    n_unique_instrument_types: 26
    n_heads: 4
    n_layers: 6
    model_dim: 1024
    hidden_dim: 4096
    include_adduct_idx: False
    include_instrument_idx: False
    dropout_rate: 0.2

trainer:
  max_epochs: 200
  devices: 4
  accelerator: "gpu"
  log_every_n_steps: 50