_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "3":
                - 17
                - 23
                - 55
            "4": 3.12.2
            "5": 0.18.0
            "6": 4.44.2
            "8":
                - 5
            "12": 0.18.0
            "13": linux-x86_64
FP_dim_mapping:
    value:
        maccs: 167
        morgan4_256: 256
        morgan4_1024: 1024
        morgan4_2048: 2048
        morgan4_4096: 4096
        morgan6_256: 256
        morgan6_1024: 1024
        morgan6_2048: 2048
        morgan6_4096: 4096
FP_pred_results_folder:
    value: ../FP_prediction_results
MLP_model_dim:
    value:
        emb_dim: 1024
        hidden_dim: 4096
class_threshold:
    value: 0.5
data_file_path:
    value: ../data/final/final_data.msp
device:
    value: cuda
eval_iter:
    value: 100
granularity:
    value: 0.1
input_dim:
    value: 10000
main_results_folder:
    value: ../results
max_mass:
    value: 1000
results_folder:
    value: ../results/../FP_prediction_results/MLP_11-09-2024-18-17
seed:
    value: 17
train_ratio:
    value: 0.8
