project: MIST
seed: 17

data:
  dir: "/data/rbg/users/klingmin/projects/MS_processing/data_splitting/canopus/splits"
  train_folder: "train_data"
  val_folder: "val_data"
  test_folder: "test_data"
  batch_size: 512
  num_workers: 4
  bin_resolution: 0.1
  max_da: 1500
  max_MS_peaks: 25
  FP_type: "MACCS"
  intensity_type: "raw"
  intensity_threshold: 5.0
  considered_atoms: ["C", "H", "O", "N", "S", "Cl", "Br", "F", "P", "I", "K", "Si", "Na"]
  n_frag_candidates: 5
  chemberta_model: "/data/rbg/users/klingmin/projects/ML_MS_analysis/pretrained_models/ChemBERTa-zinc-base-v1"

model:
  name: "binned_MS_encoder" # Choices are: binned_MS_encoder, MS_encoder, formula_encoder, frag_encoder

  train_params:
    lr: 0.0005
    weight_decay: 0.0005
    pos_weight: 10.0
    reconstruction_weight: 0.7

  binned_MS_encoder:
    model_dim: 512
    hidden_dim: 2048
    output_dim: 1024
    dropout_rate: 0.20

  MS_encoder:
    n_heads: 8
    n_layers: 8
    model_dim: 512
    hidden_dim: 2048
    dropout_rate: 0.20

trainer:
  max_epochs: 50
  devices: 4
  accelerator: "gpu"
  log_every_n_steps: 5


