project: FP_prediction
seed: 17

data:
  dir: "/data/rbg/users/klingmin/projects/MS_processing/data_splitting/nist2023/splits"
  train_folder: "train_data"
  val_folder: "val_data"
  test_folder: "test_data"
  batch_size: 512
  num_workers: 4
  bin_resolution: 0.1
  max_da: 1500
  max_MS_peaks: 25
  FP_type: "morgan4_2048"
  intensity_type: "raw"
  intensity_threshold: 5.0
  considered_atoms: ["C", "H", "O", "N", "S", "Cl", "Br", "F", "P", "I", "K", "Si", "Na"]
  mask_missing_formula: False

model:
  name: "formula_encoder" # Choices are: binned_MS_encoder, MS_encoder, formula_encoder, frag_encoder

  train_params:
    lr: 0.0005
    weight_decay: 0.0005
    pos_weight: 10.0
    reconstruction_weight: 0.8

  binned_MS_encoder:
    model_dim: 512
    hidden_dim: 2048
    output_dim: 1024
    dropout_rate: 0.15

  MS_encoder:
    n_heads: 8
    n_layers: 8
    model_dim: 512
    hidden_dim: 2048
    dropout_rate: 0.15

  frag_encoder:
    chemberta_model: "seyonec/PubChem10M_SMILES_BPE_60k"

trainer:
  max_epochs: 80
  devices: 4
  accelerator: "gpu"
  log_every_n_steps: 50


