project: FP_prediction
seed: 17

data:
  dir: "/data/rbg/users/klingmin/projects/MS_processing/data_splitting/nist2023/splits"
  train_folder: "train_data"
  val_folder: "val_data"
  test_folder: "test_data"
  batch_size: 16
  num_workers: 4
  bin_resolution: 1.0
  max_da: 1500
  max_MS_peaks: 20
  FP_type: "morgan4_2048"
  intensity_type: "binary"
  intensity_threshold: 5.0
  
model:
  name: "binned_MS_encoder"

  train_params:
    lr: 0.0004
    weight_decay: 0.1

  binned_MS_encoder:
    model_dim: 512
    hidden_dim: 2048
    output_dim: 1024
    dropout_rate: 0.15

  MS_encoder:
    n_heads: 8
    n_layers: 8
    model_dim: 512
    hidden_dim: 2048
    dropout_rate: 0.15

trainer:
  max_epochs: 100
  devices: 4
  accelerator: "gpu"
  log_every_n_steps: 50


