project: iceberg_inten
seed: 17

dataset:
  data_dir: "/data/rbg/users/klingmin/projects/MS_processing/data_BM/iceberg"
  dataset_name: "massspecgym"
  dataset_labels: "labels.tsv"
  magma_dag_folder: "magma_outputs/magma_tree"
  split_name: "random.tsv"

process_setting: 
  batch_size: 128
  num_workers: 16
  binned_targs: True
  add_hs: True
  pe_embed_k: 0
  root_encode: "gnn"

model:
  
  name: "iceberg_inten"

  params: 
    hidden_size: 256
    layers: 3
    dropout: 0.1
    mpnn_type: "GGNN"
    set_layers: 0
    frag_set_layers: 3
    gnn_layers: 4
    mlp_layers: 1
    learning_rate: 0.000736
    lr_decay_rate: 0.825
    weight_decay: 1e-07
    pe_embed_k: 0  
    pool_op: "avg"
    root_encode: "gnn"
    loss_fn: "cosine"
    binned_targs: True
    inject_early: False
    embed_adduct: True 
    encode_forms: True  
    add_hs: True

trainer:
  max_epochs: 200
  devices: 2
  accelerator: "gpu"
  log_every_n_steps: 50
  gradient_clip_val: 5 
  gradient_clip_algorithm: "value"


