project: FP_prediction_binned
seed: 17

data:
  dir: "../../data/NIST2020/MH_plus"
  batch_size: 1024
  num_workers: 2
  bin_resolution: 1.0
  max_da: 1000
  FP_type: "morgan4_2048"
# "morgan4_256": 256,
# "morgan4_1024": 1024, 
# "morgan4_2048": 2048,

model:
  train_params:
    lr: 0.0004
    weight_decay: 0.1

  binned_MS_encoder:
    n_unique_adducts: 10
    n_unique_instrument_types: 26
    model_dim: 512
    hidden_dim: 2048
    output_dim: 1024
    dropout_rate: 0.15

trainer:
  max_epochs: 1000
  devices: 4
  accelerator: "gpu"
  log_every_n_steps: 50