project: LS
seed: 17
device: 1

data:
  dir: "/data/rbg/users/klingmin/projects/MS_processing/data_splitting/massspecgym/splits"
  train_folder: "train_data"
  val_folder: "val_data"
  test_folder: "test_data"
  batch_size: 32
  num_workers: 4
  bin_resolution: 0.1
  max_da: 1500
  max_MS_peaks: 25
  FP_type: "MACCS"
  intensity_type: "raw"
  intensity_threshold: 5.0
  considered_atoms: ["C", "H", "O", "N", "S", "Cl", "Br", "F", "P", "I", "K", "Si", "Na"]
  n_frag_candidates: 5
  chemberta_model: "/data/rbg/users/klingmin/projects/ML_MS_analysis/pretrained_models/ChemBERTa-zinc-base-v1"

model:
  name: "binned_MS_encoder" # Choices are: binned_MS_encoder for now - planning to extend it to: MS_encoder, formula_encoder, frag_encoder

  train_params:
    lr: 0.0005
    weight_decay: 0.0005
    n_outer_loops: 300
    num_batches: 500
    patience: 5
    convergence_threshold: 0.003
    w_gap: 1.0
    w_ratio: 1.0 
    w_balance: 1.0
    train_ratio: 0.8

  binned_MS_encoder:
    model_dim: 512
    hidden_dim: 2048
    output_dim: 1024
    dropout_rate: 0.20

  MS_encoder:
    n_heads: 8
    n_layers: 8
    model_dim: 512
    hidden_dim: 2048
    dropout_rate: 0.20