project: LS_MS
seed: 17

data:
  dir: "/data/rbg/users/klingmin/projects/MS_processing/data/data_splits/random_split_pos"

dataprocessing: 
  batch_size: 512
  num_workers: 2
  num_batches: 10

dataloader:
  bin_resolution: 1.0
  max_da: 1000
  max_MS_peaks: 1000
  FP_type: "morgan4_256"

model:
  name: MLP
  train_params:
    n_outer_loops: 10
    patience: 1
    convergence_threshold: 0.003
    w_gap: 1.0
    w_ratio: 1.0 
    w_balance: 1.0
    train_ratio: 0.8
  
  MLP:
    n_unique_adducts: 10
    n_unique_instrument_types: 26
    model_dim: 512
    hidden_dim: 2048
    output_dim: 1024
    dropout_rate: 0.15
    include_adduct_idx: False
    include_instrument_idx: False

  MSTransformer:
    n_unique_adducts: 10
    n_unique_instrument_types: 26
    n_heads: 4
    n_layers: 6
    model_dim: 512
    hidden_dim: 2048
    output_dim: 1024
    dropout_rate: 0.15
    include_adduct_idx: False
    include_instrument_idx: False

optimizer:
  name: Adam
  lr: 0.0005
  clip_grad_norm: 0